entityName: 'Post'
entity: 'AppBundle\Entity\Post'
repository: 'AppBundle:Post'
index: 'post'
new: 'post_new'
edit: 'post_edit'
show: 'post_show'
create: 'post_create'
update: 'post_update'
delete: 'post_delete'
export: 'post_export'
view_index: 'AppBundle:post:index.html.twig'
view_new: 'AppBundle:post:new.html.twig'
view_edit: 'AppBundle:post:edit.html.twig'
view_show: 'AppBundle:post:show.html.twig'
sessionFilter: 'PostControllerFilter'
saveAndAdd: true
validator: false
fieldsindex:
    # a.id:
    #     label: 'Id'
    #     name: 'Id'
    #     type: 'integer'
    #     export: true
    a.booleano:
        label: 'Booleano'
        name: 'Booleano'
        type: 'boolean'
        export: true
    a.entero:
        label: 'Entero'
        name: 'Entero'
        type: 'integer'
        export: true
    a.smallEntero:
        label: 'Smallentero'
        name: 'Smallentero'
        type: 'smallint'
        export: true
    a.bigEntero:
        label: 'Bigentero'
        name: 'Bigentero'
        type: 'bigint'
        export: true
    a.cadena:
        label: 'Cadena'
        name: 'Cadena'
        type: 'string'
        export: true
    a.texto:
        label: 'Texto'
        name: 'Texto'
        type: 'text'
        export: true
    a.fechatiempo:
        label: 'Fechatiempo'
        name: 'Fechatiempo'
        type: 'datetime'
        date: 'Y-m-d H:i:s'
        export: true
    # a.dechatiempoz:
    #     label: 'Dechatiempoz'
    #     name: 'Dechatiempoz'
    #     type: 'datetimetz'
    #     date: 'Y-m-d H:i:s'
    #     export: true
    a.fecha:
        label: 'Fecha'
        name: 'Fecha'
        type: 'date'
        date: 'Y-m-d'
        export: true
    a.tiempo:
        label: 'Tiempo'
        name: 'Tiempo'
        type: 'time'
        date: 'H:i:s'
        export: true
    a.numerodecimal:
        label: 'Numerodecimal'
        name: 'Numerodecimal'
        type: 'decimal'
        export: true
    a.numeroconcoma:
        label: 'Numeroconcoma'
        name: 'Numeroconcoma'
        type: 'float'
        export: true
fieldsshow:
    a.id:
        label: 'Id'
        name: 'Id'
        type: 'integer'
        #class: 'col-lg-12'
        #closerow: true
    a.booleano:
        label: 'Booleano'
        name: 'Booleano'
        type: 'boolean'
        #class: 'col-lg-12'
        #closerow: true
    a.entero:
        label: 'Entero'
        name: 'Entero'
        type: 'integer'
        #class: 'col-lg-12'
        #closerow: true
    a.smallEntero:
        label: 'Smallentero'
        name: 'Smallentero'
        type: 'smallint'
        #class: 'col-lg-12'
        #closerow: true
    a.bigEntero:
        label: 'Bigentero'
        name: 'Bigentero'
        type: 'bigint'
        #class: 'col-lg-12'
        #closerow: true
    a.cadena:
        label: 'Cadena'
        name: 'Cadena'
        type: 'string'
        #class: 'col-lg-12'
        #closerow: true
    a.texto:
        label: 'Texto'
        name: 'Texto'
        type: 'text'
        #class: 'col-lg-12'
        #closerow: true
    a.fechatiempo:
        label: 'Fechatiempo'
        name: 'Fechatiempo'
        type: 'datetime'
        date: 'Y-m-d H:i:s'
        #class: 'col-lg-12'
        #closerow: true
    a.dechatiempoz:
        label: 'Dechatiempoz'
        name: 'Dechatiempoz'
        type: 'datetimetz'
        date: 'Y-m-d H:i:s'
        #class: 'col-lg-12'
        #closerow: true
    a.fecha:
        label: 'Fecha'
        name: 'Fecha'
        type: 'date'
        date: 'Y-m-d'
        #class: 'col-lg-12'
        #closerow: true
    a.tiempo:
        label: 'Tiempo'
        name: 'Tiempo'
        type: 'time'
        date: 'H:i:s'
        #class: 'col-lg-12'
        #closerow: true
    a.numerodecimal:
        label: 'Numerodecimal'
        name: 'Numerodecimal'
        type: 'decimal'
        #class: 'col-lg-12'
        #closerow: true
    a.numeroconcoma:
        label: 'Numeroconcoma'
        name: 'Numeroconcoma'
        type: 'float'
        #class: 'col-lg-12'
        #closerow: true